"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions */
import { useState } from "react";
import { toast } from "sonner";
import { deleteSubCategory, saveSubCategory, toggleSubCategoryStatus } from "./actions";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
type Category = { id: string; name: string }; type Row = { id: string; categoryId: string; name: string; slug: string; icon: string | null; description: string | null; order: number; status: "ACTIVE" | "INACTIVE"; blogCount: number };
const empty = { categoryId: "", name: "", slug: "", icon: "", description: "", order: 0, status: "ACTIVE" as const };
export function SubCategoryManager({ categories, rows }: { categories: Category[]; rows: Row[] }) { const [editing, setEditing] = useState<Row | null>(null); const [open, setOpen] = useState(false); const [deleting, setDeleting] = useState<Row | null>(null); const submit = async (data: FormData) => { if (editing) data.set("id", editing.id); const result = await saveSubCategory(data); result.success ? (toast.success(result.message), setOpen(false), setEditing(null)) : toast.error(result.message); }; const remove = async () => { if (!deleting) return; const result = await deleteSubCategory(deleting.id); result.success ? (toast.success(result.message), setDeleting(null)) : toast.error(result.message); }; const toggle = async (row: Row) => { const result = await toggleSubCategoryStatus(row.id, row.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"); result.success ? toast.success(result.message) : toast.error(result.message); };
return <><div className="flex justify-end"><Button onClick={() => { setEditing(null); setOpen(true); }}>Add subcategory</Button></div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[760px] text-sm"><thead className="border-b bg-muted/40 text-left text-xs uppercase text-muted-foreground"><tr><th className="p-4">Name</th><th className="p-4">Category</th><th className="p-4">Status</th><th className="p-4">Blogs</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{rows.map((row) => <tr key={row.id}><td className="p-4"><b>{row.name}</b><p className="mt-1 font-mono text-xs text-muted-foreground">{row.slug}</p></td><td className="p-4 text-muted-foreground">{categories.find((c) => c.id === row.categoryId)?.name}</td><td className="p-4"><button className="text-sm text-sky-700 dark:text-sky-300" onClick={() => void toggle(row)}>{row.status === "ACTIVE" ? "Active" : "Inactive"}</button></td><td className="p-4">{row.blogCount}</td><td className="p-4 text-right"><Button size="sm" variant="ghost" onClick={() => { setEditing(row); setOpen(true); }}>Edit</Button><Button size="sm" variant="ghost" onClick={() => setDeleting(row)}>Delete</Button></td></tr>)}</tbody></table></div><Editor categories={categories} onOpenChange={setOpen} onSubmit={submit} open={open} values={editing ?? empty} /><Dialog open={Boolean(deleting)} onOpenChange={(v) => !v && setDeleting(null)}><DialogContent><DialogHeader><DialogTitle>Delete subcategory?</DialogTitle><DialogDescription>Deleting “{deleting?.name}” is permanent. Delete or reassign its blogs first.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleting(null)}>Cancel</Button><Button variant="destructive" onClick={() => void remove()}>Delete</Button></DialogFooter></DialogContent></Dialog></>; }
function Editor({ categories, onOpenChange, onSubmit, open, values }: { categories: Category[]; onOpenChange: (v: boolean) => void; onSubmit: (d: FormData) => Promise<void>; open: boolean; values: typeof empty | Row }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{"id" in values ? "Edit subcategory" : "Add subcategory"}</DialogTitle></DialogHeader><form action={onSubmit} className="grid gap-3"><select className="input" defaultValue={values.categoryId} name="categoryId" required><option value="">Select category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="input" defaultValue={values.name} name="name" placeholder="Name" required /><input className="input" defaultValue={values.slug} name="slug" placeholder="Slug" /><input className="input" defaultValue={values.icon || ""} name="icon" placeholder="Icon" /><textarea className="input min-h-20" defaultValue={values.description || ""} name="description" placeholder="Description" /><input className="input" defaultValue={values.order} min="0" name="order" type="number" /><select className="input" defaultValue={values.status} name="status"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><DialogFooter><Button variant="outline" type="button" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit">Save</Button></DialogFooter></form></DialogContent></Dialog>; }
