"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { saveProject } from "@/app/(protected)/admin/projects/actions";
type Values = { title: string; slug: string; shortDescription: string; description: string; technologies: string; githubUrl: string; liveDemoUrl: string; coverImage: string; galleryImages: string; featured: boolean; status: "DRAFT" | "PUBLISHED"; seoTitle: string; seoDescription: string };
export function ProjectEditor({ project }: { project?: Partial<Values> & { id: string } }) { const [pending, start] = useTransition(); const [error, setError] = useState(""); const router = useRouter(); const form = useForm<Values>({ defaultValues: { title: "", slug: "", shortDescription: "", description: "", technologies: "", githubUrl: "", liveDemoUrl: "", coverImage: "", galleryImages: "", featured: false, status: "DRAFT", seoTitle: "", seoDescription: "", ...project } }); const submit = (v: Values) => start(async () => { const result = await saveProject({ ...v, technologies: v.technologies.split(",").map(x => x.trim()).filter(Boolean), galleryImages: v.galleryImages.split("\n").map(x => x.trim()).filter(Boolean) }, project?.id); if (result?.error) setError(result.error); else router.push("/admin/projects"); }); return <form className="space-y-6" onSubmit={form.handleSubmit(submit)}><section className="grid gap-4 rounded-xl border border-white/10 bg-white/[.04] p-5 md:grid-cols-2"><Field label="Title" input={form.register("title", { required: true })} /><Field label="Slug" input={form.register("slug")} placeholder="Generated from title" /><Field label="Short description" input={form.register("shortDescription", { required: true })} /><Field label="Technologies" input={form.register("technologies", { required: true })} placeholder="React, Next.js, PostgreSQL" /><Text label="Rich description (HTML or Markdown)" input={form.register("description", { required: true })} /><div className="grid gap-4"><Field label="GitHub URL" input={form.register("githubUrl")} /><Field label="Live demo URL" input={form.register("liveDemoUrl")} /><Field label="Cover image URL" input={form.register("coverImage")} /><Text label="Gallery image URLs (one per line)" input={form.register("galleryImages")} /></div></section><section className="grid gap-4 rounded-xl border border-white/10 bg-white/[.04] p-5 md:grid-cols-2"><Field label="SEO title" input={form.register("seoTitle")} /><Text label="SEO description" input={form.register("seoDescription")} /><label className="text-sm text-slate-200">Status<select className="mt-2 block w-full rounded border border-white/15 bg-slate-950 p-2" {...form.register("status")}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></label><label className="flex items-center gap-2 text-sm text-slate-200"><input type="checkbox" {...form.register("featured")} />Feature this project</label></section>{error ? <p className="text-sm text-rose-200">{error}</p> : null}<button className="rounded-lg bg-sky-300 px-4 py-2 font-semibold text-slate-950 disabled:opacity-60" disabled={pending}>{pending ? "Saving…" : "Save project"}</button></form>; }
function Field({ label, input, placeholder }: { label: string; input: ReturnType<typeof useForm<Values>>["register"] extends (...args: never[]) => infer R ? R : never; placeholder?: string }) { return <label className="text-sm text-slate-200">{label}<input className="mt-2 block w-full rounded border border-white/15 bg-slate-950 p-2" placeholder={placeholder} {...input} /></label>; }
function Text({ label, input }: { label: string; input: ReturnType<typeof useForm<Values>>["register"] extends (...args: never[]) => infer R ? R : never }) { return <label className="text-sm text-slate-200">{label}<textarea className="mt-2 min-h-28 w-full rounded border border-white/15 bg-slate-950 p-2" {...input} /></label>; }
