"use server";
import { Prisma, ProductStatus, RoleName } from "@/generated/prisma/client";
import { requireRole } from "@/lib/auth/authorization";
import { prisma } from "@/lib/prisma";
import { productCategorySchema, productSchema } from "@/lib/validations/shop";
import { revalidatePath } from "next/cache";
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
export async function saveProduct(input: unknown, id?: string) { const s = await requireRole([RoleName.ADMIN, RoleName.SUPER_ADMIN]); const p = productSchema.safeParse(input); if (!p.success) return { error: "Review product fields." }; const d = p.data; const data = { ...d, slug: slugify(d.slug || d.name), categoryId: d.categoryId || null, price: new Prisma.Decimal(d.price), compareAtPrice: d.compareAtPrice === undefined ? null : new Prisma.Decimal(d.compareAtPrice), status: d.status as ProductStatus }; try { const product = id ? await prisma.product.update({ where: { id }, data }) : await prisma.product.create({ data }); await prisma.auditLog.create({ data: { actorId: s.user.id, event: id ? "PRODUCT_UPDATED" : "PRODUCT_CREATED", metadata: { id: product.id, sku: product.sku } } }); revalidatePath("/shop"); revalidatePath(`/shop/${product.slug}`); revalidatePath("/admin/products"); return { id: product.id }; } catch { return { error: "Product SKU and slug must be unique." }; } }
export async function deleteProduct(id: string) { const s = await requireRole([RoleName.ADMIN, RoleName.SUPER_ADMIN]); await prisma.product.delete({ where: { id } }); await prisma.auditLog.create({ data: { actorId: s.user.id, event: "PRODUCT_DELETED", metadata: { id } } }); revalidatePath("/shop"); revalidatePath("/admin/products"); }
export async function saveProductCategory(input: unknown) { const s = await requireRole([RoleName.ADMIN, RoleName.SUPER_ADMIN]); const p = productCategorySchema.safeParse(input); if (!p.success) return { error: "Review category fields." }; const d = p.data; try { const category = await prisma.productCategory.create({ data: { ...d, slug: slugify(d.slug || d.name), description: d.description || null, image: d.image || null } }); await prisma.auditLog.create({ data: { actorId: s.user.id, event: "PRODUCT_CATEGORY_CREATED", metadata: { id: category.id } } }); revalidatePath("/shop"); revalidatePath("/admin/products"); return { id: category.id }; } catch { return { error: "Category name and slug must be unique." }; } }
