"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions */

import { Edit3, MoreHorizontal, Power, Trash2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { toast } from "sonner";

import { deleteBlog, toggleBlogPublished } from "@/app/(protected)/admin/blog/cms-actions";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

type BlogRow = { id: string; title: string; slug: string; published: boolean; featured: boolean; views: number; updatedAt: string; category: { name: string }; subCategory: { name: string } };
export function BlogTable({ blogs }: { blogs: BlogRow[] }) { const [deleting, setDeleting] = useState<BlogRow | null>(null); const [pending, setPending] = useState<string | null>(null); const remove = async () => { if (!deleting) return; setPending(deleting.id); const result = await deleteBlog(deleting.id); setPending(null); result.success ? (toast.success(result.message), setDeleting(null)) : toast.error(result.message); }; const toggle = async (blog: BlogRow) => { setPending(blog.id); const result = await toggleBlogPublished(blog.id, !blog.published); setPending(null); result.success ? toast.success(result.message) : toast.error(result.message); };
return <><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[860px] text-left text-sm"><thead className="border-b bg-muted/40 text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-3">Blog</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Views</th><th className="px-5 py-3">Updated</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{blogs.map((blog) => <tr key={blog.id}><td className="px-5 py-4"><p className="font-medium">{blog.title}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{blog.slug}</p></td><td className="px-5 py-4 text-muted-foreground">{blog.category.name}<span className="mx-1">/</span>{blog.subCategory.name}</td><td className="px-5 py-4"><span className={blog.published ? "text-emerald-600 dark:text-emerald-300" : "text-muted-foreground"}>{blog.published ? "Published" : "Draft"}</span>{blog.featured ? <span className="ml-2 text-xs text-sky-600 dark:text-sky-300">Featured</span> : null}</td><td className="px-5 py-4 text-muted-foreground">{blog.views}</td><td className="px-5 py-4 text-xs text-muted-foreground">{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(blog.updatedAt))}</td><td className="px-5 py-4 text-right"><DropdownMenu><DropdownMenuTrigger render={<Button aria-label={`Actions for ${blog.title}`} size="icon-sm" variant="ghost" />}><MoreHorizontal className="size-4" /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem render={<Link href={`/admin/blog/${blog.id}`} />}><Edit3 className="size-4" />Edit</DropdownMenuItem><DropdownMenuItem disabled={pending === blog.id} onClick={() => void toggle(blog)}><Power className="size-4" />{blog.published ? "Move to draft" : "Publish"}</DropdownMenuItem><DropdownMenuItem variant="destructive" onClick={() => setDeleting(blog)}><Trash2 className="size-4" />Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu></td></tr>)}</tbody></table></div><Dialog open={Boolean(deleting)} onOpenChange={(open) => !open && setDeleting(null)}><DialogContent><DialogHeader><DialogTitle>Delete blog?</DialogTitle><DialogDescription>This permanently deletes “{deleting?.title}”.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleting(null)}>Cancel</Button><Button disabled={Boolean(pending)} onClick={() => void remove()} variant="destructive">Delete blog</Button></DialogFooter></DialogContent></Dialog></>;
}
