import Link from "next/link";
import { Plus } from "lucide-react";
import { Prisma } from "@/generated/prisma/client";
import { prisma } from "@/lib/prisma";
import { BlogTable } from "./blog-table";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const pageSize = 12;
export default async function BlogAdminPage({ searchParams }: { searchParams: Promise<{ search?: string; published?: string; page?: string }> }) { const params = await searchParams; const search = params.search?.trim() || ""; const published = params.published === "true" ? true : params.published === "false" ? false : undefined; const page = Math.max(1, Number(params.page) || 1); const where: Prisma.BlogWhereInput = { ...(published === undefined ? {} : { published }), ...(search ? { OR: [{ title: { contains: search, mode: "insensitive" } }, { slug: { contains: search, mode: "insensitive" } }] } : {}) }; const [total, blogs] = await Promise.all([prisma.blog.count({ where }), prisma.blog.findMany({ where, orderBy: { updatedAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize, select: { id: true, title: true, slug: true, published: true, featured: true, views: true, updatedAt: true, category: { select: { name: true } }, subCategory: { select: { name: true } } } })]); const totalPages = Math.max(1, Math.ceil(total / pageSize)); return <div className="space-y-6 p-5 sm:p-8 lg:p-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold tracking-[.16em] text-sky-600 uppercase dark:text-sky-300">Content</p><h1 className="mt-2 text-3xl font-semibold">Blogs</h1><p className="mt-2 text-sm text-muted-foreground">Documentation-quality embedded engineering articles.</p></div><Button render={<Link href="/admin/blog/new" />}><Plus className="size-4" />New blog</Button></div><Card><CardHeader><CardTitle>Blog library</CardTitle><CardDescription>{total} blog{total === 1 ? "" : "s"} matching the current filters.</CardDescription></CardHeader><CardContent className="space-y-5"><form className="grid gap-3 sm:grid-cols-[1fr_10rem_auto]" method="get"><input className="input" defaultValue={search} name="search" placeholder="Search title or slug" /><select className="input" defaultValue={params.published ?? ""} name="published"><option value="">All statuses</option><option value="true">Published</option><option value="false">Draft</option></select><Button type="submit" variant="outline">Filter</Button></form>{blogs.length ? <BlogTable blogs={blogs.map((item) => ({ ...item, updatedAt: item.updatedAt.toISOString() }))} /> : <div className="grid min-h-56 place-items-center rounded-xl border border-dashed text-sm text-muted-foreground">No blogs found.</div>}{totalPages > 1 ? <Pagination page={page} search={search} published={params.published} totalPages={totalPages} /> : null}</CardContent></Card></div>; }
function Pagination({ page, search, published, totalPages }: { page: number; search: string; published?: string; totalPages: number }) { const url = (next: number) => { const query = new URLSearchParams({ page: String(next) }); if (search) query.set("search", search); if (published) query.set("published", published); return `/admin/blog?${query}`; }; return <div className="flex justify-between border-t pt-5 text-sm"><span className="text-muted-foreground">Page {page} of {totalPages}</span><span className="flex gap-2">{page > 1 ? <Link className="rounded-lg border px-3 py-1.5" href={url(page - 1)}>Previous</Link> : null}{page < totalPages ? <Link className="rounded-lg border px-3 py-1.5" href={url(page + 1)}>Next</Link> : null}</span></div>; }
