packages:
  - 'apps/*'

allowBuilds:
  '@firebase/util': set this to true or false
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  protobufjs: set this to true or false
  sharp: true
  unrs-resolver: true
