import Link from "next/link";

type Category = { id: string; name: string; slug: string; _count: { blogs: number } };
type Recent = { slug: string; title: string; updatedAt: Date };

export function BlogSidebar({ categories, featured, recent, search }: { categories: Category[]; featured: Recent[]; recent: Recent[]; search?: string }) {
  return <aside className="space-y-6"><section className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Search articles</h2><form className="mt-4" action="/blog"><input className="input" defaultValue={search} name="search" placeholder="Search VJtronix blog" /><button className="mt-2 w-full rounded-lg bg-sky-500 px-3 py-2 text-sm font-semibold text-white hover:bg-sky-600" type="submit">Search</button></form></section><SidebarList title="Categories">{categories.map((category) => <Link className="flex justify-between gap-3 text-sm text-muted-foreground transition hover:text-foreground" href={`/blog?category=${category.slug}`} key={category.id}><span>{category.name}</span><span>{category._count.blogs}</span></Link>)}</SidebarList><SidebarList title="Recent posts">{recent.map((blog) => <Link className="text-sm font-medium leading-5 text-foreground transition hover:text-sky-600 dark:hover:text-sky-300" href={`/blog/${blog.slug}`} key={blog.slug}>{blog.title}<span className="mt-1 block text-xs font-normal text-muted-foreground">{formatDate(blog.updatedAt)}</span></Link>)}</SidebarList><SidebarList title="Featured posts">{featured.map((blog) => <Link className="text-sm font-medium leading-5 text-foreground transition hover:text-sky-600 dark:hover:text-sky-300" href={`/blog/${blog.slug}`} key={blog.slug}>{blog.title}</Link>)}</SidebarList></aside>;
}
function SidebarList({ children, title }: { children: React.ReactNode; title: string }) { return <section className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">{title}</h2><div className="mt-4 grid gap-3">{children}</div></section>; }
function formatDate(date: Date) { return new Intl.DateTimeFormat("en", { day: "numeric", month: "short" }).format(date); }
