"use server";
import { ProjectStatus, RoleName } from "@/generated/prisma/client";
import { requireRole } from "@/lib/auth/authorization";
import { prisma } from "@/lib/prisma";
import { projectSchema } from "@/lib/validations/projects";
import { revalidatePath } from "next/cache";
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
export async function saveProject(input: unknown, id?: string) { const session = await requireRole([RoleName.ADMIN, RoleName.SUPER_ADMIN]); const parsed = projectSchema.safeParse(input); if (!parsed.success) return { error: "Review the project fields." }; const d = parsed.data; try { const project = id ? await prisma.project.update({ where: { id }, data: { ...d, slug: slugify(d.slug || d.title), githubUrl: d.githubUrl || null, liveDemoUrl: d.liveDemoUrl || null, coverImage: d.coverImage || null, seoTitle: d.seoTitle || null, seoDescription: d.seoDescription || null, status: d.status as ProjectStatus } }) : await prisma.project.create({ data: { ...d, slug: slugify(d.slug || d.title), githubUrl: d.githubUrl || null, liveDemoUrl: d.liveDemoUrl || null, coverImage: d.coverImage || null, seoTitle: d.seoTitle || null, seoDescription: d.seoDescription || null, status: d.status as ProjectStatus } }); await prisma.auditLog.create({ data: { actorId: session.user.id, event: id ? "PROJECT_UPDATED" : "PROJECT_CREATED", metadata: { id: project.id, slug: project.slug } } }); revalidatePath("/projects"); revalidatePath(`/projects/${project.slug}`); revalidatePath("/admin/projects"); return { id: project.id }; } catch { return { error: "A project with this slug already exists." }; } }
export async function deleteProject(id: string) { const s = await requireRole([RoleName.ADMIN, RoleName.SUPER_ADMIN]); await prisma.project.delete({ where: { id } }); await prisma.auditLog.create({ data: { actorId: s.user.id, event: "PROJECT_DELETED", metadata: { id } } }); revalidatePath("/projects"); revalidatePath("/admin/projects"); }
export async function toggleFeatured(id: string) { const s = await requireRole([RoleName.ADMIN, RoleName.SUPER_ADMIN]); const current = await prisma.project.findUniqueOrThrow({ where: { id }, select: { featured: true } }); await prisma.project.update({ where: { id }, data: { featured: !current.featured } }); await prisma.auditLog.create({ data: { actorId: s.user.id, event: "PROJECT_FEATURED_CHANGED", metadata: { id, featured: !current.featured } } }); revalidatePath("/projects"); revalidatePath("/admin/projects"); }
