"use client";

import { useEffect, useTransition } from "react";
import { useForm } from "react-hook-form";
import { saveCourse } from "./actions";

export type CourseValues = { title: string; slug: string; shortDescription: string; description: string; thumbnail: string; categoryId: string; level: "BEGINNER" | "INTERMEDIATE" | "ADVANCED"; language: string; duration: number; price: number; isFree: boolean; status: "DRAFT" | "PUBLISHED" | "ARCHIVED" };
type Category = { id: string; name: string };
const field = "mt-1.5 w-full rounded-lg border border-white/15 bg-slate-950 px-3 py-2 text-sm text-white outline-none focus:border-sky-300";
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export function CourseEditor({ categories, course }: { categories: Category[]; course?: CourseValues & { id: string } }) {
  const [pending, startTransition] = useTransition(); const form = useForm<CourseValues>({ defaultValues: course ?? { title: "", slug: "", shortDescription: "", description: "", thumbnail: "", categoryId: "", level: "BEGINNER", language: "English", duration: 0, price: 0, isFree: true, status: "DRAFT" } });
  const free = form.watch("isFree"); const title = form.watch("title"); const manualSlug = form.watch("slug");
  useEffect(() => { if (!course && !manualSlug) form.setValue("slug", slugify(title)); }, [course, form, manualSlug, title]);
  function submit(values: CourseValues) { startTransition(async () => { const result = await saveCourse(values, course?.id); if (result?.error) form.setError("root", { message: result.error }); }); }
  return <form className="space-y-6" onSubmit={form.handleSubmit(submit)}><div className="grid gap-6 xl:grid-cols-[1fr_20rem]"><section className="space-y-5 rounded-xl border border-white/10 bg-white/[.04] p-5"><Label label="Title"><input className={field} {...form.register("title")} /></Label><Label label="Slug"><input className={field} {...form.register("slug")} /><Hint>Generated from the title; you can customize it.</Hint></Label><Label label="Short description"><textarea className={`${field} min-h-24`} {...form.register("shortDescription")} /></Label><Label label="Description"><textarea className={`${field} min-h-56`} {...form.register("description")} /></Label></section><aside className="space-y-5 rounded-xl border border-white/10 bg-white/[.04] p-5"><Label label="Thumbnail URL"><input className={field} placeholder="https://…" {...form.register("thumbnail")} /></Label><Label label="Category"><select className={field} {...form.register("categoryId")}><option value="">Uncategorized</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Label><Label label="Level"><select className={field} {...form.register("level")}><option value="BEGINNER">Beginner</option><option value="INTERMEDIATE">Intermediate</option><option value="ADVANCED">Advanced</option></select></Label><Label label="Language"><input className={field} {...form.register("language")} /></Label><Label label="Duration (minutes)"><input className={field} min="0" type="number" {...form.register("duration", { valueAsNumber: true })} /></Label><Label label="Status"><select className={field} {...form.register("status")}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></Label><label className="flex cursor-pointer items-center gap-2 text-sm text-slate-200"><input type="checkbox" {...form.register("isFree")} />Free course</label>{!free ? <Label label="Price"><input className={field} min="0" step="0.01" type="number" {...form.register("price", { valueAsNumber: true })} /></Label> : null}<p className="text-sm text-rose-200">{form.formState.errors.root?.message}</p><button className="w-full rounded-lg bg-sky-300 px-3 py-2 font-semibold text-slate-950 disabled:opacity-60" disabled={pending} type="submit">{pending ? "Saving…" : "Save course"}</button></aside></div></form>;
}
function Label({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-slate-200">{label}{children}</label>; }
function Hint({ children }: { children: React.ReactNode }) { return <span className="mt-1 block text-xs font-normal text-slate-500">{children}</span>; }
