"use client";

import { useState, useTransition } from "react";
import { GripVertical, Plus, Trash2 } from "lucide-react";
import { deleteLesson, deleteModule, reorderLessons, reorderModules, saveLesson, saveModule } from "./actions";

type Lesson = { id: string; title: string; slug: string; content: string; videoUrl: string | null; duration: number; isPreview: boolean; order: number };
type Module = { id: string; title: string; description: string | null; order: number; lessons: Lesson[] };
const input = "mt-1 w-full rounded border border-white/15 bg-slate-950 px-2 py-1.5 text-sm text-white";

export function CurriculumManager({ courseId, modules: initial }: { courseId: string; modules: Module[] }) {
  const [modules, setModules] = useState(initial); const [pending, startTransition] = useTransition(); const [moduleDraft, setModuleDraft] = useState({ title: "", description: "" }); const [lessonFor, setLessonFor] = useState<string | null>(null); const [dragging, setDragging] = useState<string | null>(null);
  const moveModule = (target: string) => { if (!dragging || dragging === target) return; const next = [...modules]; const from = next.findIndex((item) => item.id === dragging); const to = next.findIndex((item) => item.id === target); next.splice(to, 0, next.splice(from, 1)[0]); setModules(next); startTransition(() => reorderModules(courseId, next.map((item) => item.id))); setDragging(null); };
  const submitModule = () => startTransition(async () => { const result = await saveModule(courseId, moduleDraft); if (result?.id) { setModules([...modules, { id: result.id, title: moduleDraft.title, description: moduleDraft.description || null, order: modules.length + 1, lessons: [] }]); setModuleDraft({ title: "", description: "" }); } });
  return <section className="rounded-xl border border-white/10 bg-white/[.04] p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold text-white">Curriculum</h2><p className="text-sm text-slate-400">Drag modules or lessons to set their learning order.</p></div></div><div className="mt-5 space-y-3">{modules.map((module) => <ModuleCard key={module.id} module={module} courseId={courseId} pending={pending} onDelete={() => startTransition(async () => { await deleteModule(courseId, module.id); setModules(modules.filter((item) => item.id !== module.id)); })} onDragEnd={moveModule} onDragStart={setDragging} setModules={setModules} showLesson={lessonFor === module.id} toggleLesson={() => setLessonFor(lessonFor === module.id ? null : module.id)} />)}</div><div className="mt-5 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input className={input} onChange={(e) => setModuleDraft({ ...moduleDraft, title: e.target.value })} placeholder="New module title" value={moduleDraft.title} /><input className={input} onChange={(e) => setModuleDraft({ ...moduleDraft, description: e.target.value })} placeholder="Description (optional)" value={moduleDraft.description} /><button className="rounded bg-sky-300 px-3 py-2 text-sm font-semibold text-slate-950 disabled:opacity-60" disabled={!moduleDraft.title || pending} onClick={submitModule} type="button"><Plus className="mr-1 inline size-4" />Add module</button></div></section>;
}
function ModuleCard({ courseId, module, onDelete, onDragEnd, onDragStart, pending, setModules, showLesson, toggleLesson }: { courseId: string; module: Module; pending: boolean; showLesson: boolean; toggleLesson: () => void; onDelete: () => void; onDragStart: (id: string) => void; onDragEnd: (id: string) => void; setModules: React.Dispatch<React.SetStateAction<Module[]>> }) {
  const [draft, setDraft] = useState({ title: "", slug: "", content: "", videoUrl: "", duration: 0, isPreview: false }); const [drag, setDrag] = useState<string | null>(null); const [working, start] = useTransition();
  const moveLesson = (target: string) => { if (!drag || drag === target) return; const lessons = [...module.lessons]; const from = lessons.findIndex((item) => item.id === drag); const to = lessons.findIndex((item) => item.id === target); lessons.splice(to, 0, lessons.splice(from, 1)[0]); setModules((all) => all.map((item) => item.id === module.id ? { ...item, lessons } : item)); start(() => reorderLessons(courseId, module.id, lessons.map((item) => item.id))); setDrag(null); };
  const submit = () => start(async () => { const result = await saveLesson(courseId, module.id, draft); if (result?.id) { setModules((all) => all.map((item) => item.id === module.id ? { ...item, lessons: [...item.lessons, { ...draft, id: result.id, videoUrl: draft.videoUrl || null, order: item.lessons.length + 1 }] } : item)); setDraft({ title: "", slug: "", content: "", videoUrl: "", duration: 0, isPreview: false }); } });
  return <div className="rounded-lg border border-white/10 bg-slate-950/60" draggable onDragEnd={() => onDragEnd(module.id)} onDragOver={(e) => e.preventDefault()} onDragStart={() => onDragStart(module.id)}><div className="flex items-center gap-2 p-3"><GripVertical className="size-4 text-slate-500" /><div className="min-w-0 flex-1"><p className="font-medium text-slate-100">{module.order}. {module.title}</p>{module.description ? <p className="text-xs text-slate-500">{module.description}</p> : null}</div><button className="text-xs text-sky-200" onClick={toggleLesson} type="button">{showLesson ? "Close" : "Add lesson"}</button><button className="text-rose-200" onClick={onDelete} type="button"><Trash2 className="size-4" /></button></div><div className="border-t border-white/10 px-3">{module.lessons.map((lesson) => <div className="flex items-center gap-2 border-b border-white/5 py-2 text-sm" draggable key={lesson.id} onDragEnd={() => moveLesson(lesson.id)} onDragOver={(e) => e.preventDefault()} onDragStart={() => setDrag(lesson.id)}><GripVertical className="size-3.5 text-slate-600" /><span className="flex-1 text-slate-300">{lesson.order}. {lesson.title}</span><span className="text-xs text-slate-500">{lesson.duration} min{lesson.isPreview ? " · Preview" : ""}</span><button className="text-rose-200" onClick={() => start(async () => { await deleteLesson(courseId, lesson.id); setModules((all) => all.map((item) => item.id === module.id ? { ...item, lessons: item.lessons.filter((current) => current.id !== lesson.id) } : item)); })} type="button"><Trash2 className="size-3.5" /></button></div>)}</div>{showLesson ? <div className="grid gap-2 border-t border-white/10 p-3 md:grid-cols-2"><input className={input} onChange={(e) => setDraft({ ...draft, title: e.target.value })} placeholder="Lesson title" value={draft.title} /><input className={input} onChange={(e) => setDraft({ ...draft, slug: e.target.value })} placeholder="Slug (optional)" value={draft.slug} /><textarea className={input} onChange={(e) => setDraft({ ...draft, content: e.target.value })} placeholder="Lesson content" value={draft.content} /><input className={input} onChange={(e) => setDraft({ ...draft, videoUrl: e.target.value })} placeholder="Video URL" value={draft.videoUrl} /><input className={input} min="0" onChange={(e) => setDraft({ ...draft, duration: Number(e.target.value) })} placeholder="Duration (minutes)" type="number" value={draft.duration} /><label className="flex items-center gap-2 text-sm text-slate-300"><input checked={draft.isPreview} onChange={(e) => setDraft({ ...draft, isPreview: e.target.checked })} type="checkbox" />Preview lesson</label><button className="rounded bg-sky-300 px-3 py-2 text-sm font-semibold text-slate-950 disabled:opacity-60" disabled={!draft.title || !draft.content || working || pending} onClick={submit} type="button">Add lesson</button></div> : null}</div>;
}
