CREATE TYPE "ProjectStatus" AS ENUM ('DRAFT', 'PUBLISHED');
CREATE TYPE "ProductStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED');

CREATE TABLE "Project" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "slug" TEXT NOT NULL, "shortDescription" TEXT NOT NULL, "description" TEXT NOT NULL, "technologies" TEXT[] NOT NULL, "githubUrl" TEXT, "liveDemoUrl" TEXT, "coverImage" TEXT, "galleryImages" TEXT[] NOT NULL, "featured" BOOLEAN NOT NULL DEFAULT false, "status" "ProjectStatus" NOT NULL DEFAULT 'DRAFT', "seoTitle" TEXT, "seoDescription" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Project_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Project_slug_key" ON "Project"("slug"); CREATE INDEX "Project_status_featured_updatedAt_idx" ON "Project"("status", "featured", "updatedAt");
CREATE TABLE "ProductCategory" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "description" TEXT, "image" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ProductCategory_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ProductCategory_name_key" ON "ProductCategory"("name"); CREATE UNIQUE INDEX "ProductCategory_slug_key" ON "ProductCategory"("slug");
CREATE TABLE "Product" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "shortDescription" TEXT NOT NULL, "description" TEXT NOT NULL, "sku" TEXT NOT NULL, "price" DECIMAL(10,2) NOT NULL, "compareAtPrice" DECIMAL(10,2), "stock" INTEGER NOT NULL DEFAULT 0, "images" TEXT[] NOT NULL, "galleryImages" TEXT[] NOT NULL, "status" "ProductStatus" NOT NULL DEFAULT 'DRAFT', "featured" BOOLEAN NOT NULL DEFAULT false, "categoryId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Product_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug"); CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku"); CREATE INDEX "Product_status_categoryId_updatedAt_idx" ON "Product"("status", "categoryId", "updatedAt"); CREATE INDEX "Product_featured_status_idx" ON "Product"("featured", "status"); ALTER TABLE "Product" ADD CONSTRAINT "Product_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ProductCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "Cart" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Cart_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Cart_userId_key" ON "Cart"("userId"); ALTER TABLE "Cart" ADD CONSTRAINT "Cart_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "CartItem" ("id" TEXT NOT NULL, "cartId" TEXT NOT NULL, "productId" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CartItem_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "CartItem_cartId_productId_key" ON "CartItem"("cartId", "productId"); CREATE INDEX "CartItem_productId_idx" ON "CartItem"("productId"); ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_cartId_fkey" FOREIGN KEY ("cartId") REFERENCES "Cart"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "Wishlist" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "productId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Wishlist_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "Wishlist_userId_productId_key" ON "Wishlist"("userId", "productId"); CREATE INDEX "Wishlist_productId_idx" ON "Wishlist"("productId"); ALTER TABLE "Wishlist" ADD CONSTRAINT "Wishlist_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Wishlist" ADD CONSTRAINT "Wishlist_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "Order" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "status" "OrderStatus" NOT NULL DEFAULT 'PENDING', "subtotal" DECIMAL(10,2) NOT NULL, "total" DECIMAL(10,2) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Order_pkey" PRIMARY KEY ("id")); CREATE INDEX "Order_userId_createdAt_idx" ON "Order"("userId", "createdAt"); ALTER TABLE "Order" ADD CONSTRAINT "Order_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "OrderItem" ("id" TEXT NOT NULL, "orderId" TEXT NOT NULL, "productId" TEXT, "title" TEXT NOT NULL, "sku" TEXT NOT NULL, "unitPrice" DECIMAL(10,2) NOT NULL, "quantity" INTEGER NOT NULL, CONSTRAINT "OrderItem_pkey" PRIMARY KEY ("id")); CREATE INDEX "OrderItem_productId_idx" ON "OrderItem"("productId"); ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "AiPromptTemplate" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "prompt" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AiPromptTemplate_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "AiPromptTemplate_name_key" ON "AiPromptTemplate"("name");
CREATE TABLE "AiFaq" ("id" TEXT NOT NULL, "question" TEXT NOT NULL, "answer" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AiFaq_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "AiFaq_question_key" ON "AiFaq"("question");
CREATE TABLE "AiConfiguration" ("id" TEXT NOT NULL DEFAULT 'default', "welcomeMessage" TEXT NOT NULL, "systemPrompt" TEXT NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AiConfiguration_pkey" PRIMARY KEY ("id"));
